# Generated by Django 4.0.5 on 2022-06-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('reponse1', models.CharField(max_length=300)),
                ('reponse2', models.CharField(max_length=300)),
                ('reponse3', models.CharField(max_length=300)),
                ('reponse4', models.CharField(max_length=300)),
                ('bonne_reponse', models.CharField(max_length=300)),
            ],
        ),
    ]
